-- ===================================================================================
-- PROJECT: Exploratory Data Analysis (EDA) on Retail Data Warehouse
-- DESCRIPTION: This script performs data profiling, dimensional validation, KPI metrics 
--              generation, magnitude distribution, and ranking analysis on the 'gold' schema.
-- ===================================================================================

---------------Dimensions & Measures----------------

--------EDA(Exploratory Data Analytics-------------

--1.Database Exploration

	--Explore ALL Objects in the Database
	SELECT * FROM INFORMATION_SCHEMA.TABLES

	--Explore ALL columns in the Database

	SELECT * FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'dim_customers'

--2.Dimensions Exploration
	--USE DISTINCT[Dimension]

	--Explore All Countries our customers come from
	SELECT DISTINCT COUNTRY FROM gold.dim_customers

	--Explore All Category FROM gold.dim_products
	SELECT DISTINCT category, subcategory,product_name FROM gold.dim_products
	ORDER BY 1,2,3

--3.Date Exploration
	--MIN/MAX[Date Dimension]

	--Find the date of the first and last_order
	--How many years of sales are available
	SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years
	FROM gold.fact_sales

	--Find the youngest and oldest customer
	SELECT
	MIN(birthdate) AS oldest_birthdate,
	DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_date,
	MAX(birthdate) AS youngest_birthdate,
	DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_date
	FROM gold.dim_customers

--4. Measures Exploration
	--Aggregate_function[Measure]
	--Find the total sales
	SELECT 
	SUM(sales_amount) AS total_sales 
	FROM gold.fact_sales

	--Find how many items are sold
	SELECT 
	SUM(quantity) AS total_quantity
	FROM gold.fact_sales

	--Find the average selling price
	SELECT 
	AVG(price) AS avg_price
	FROM gold.fact_sales

	--Find the total number of orders
	SELECT
	COUNT(DISTINCT order_number) AS total_orders
	FROM gold.fact_sales

	--Find the total number of products
	SELECT
	COUNT(DISTINCT product_key) AS total_products FROM gold.dim_products

	--Find the total number of customers
	SELECT
	COUNT(DISTINCT customer_key) AS total_customers 
	FROM gold.dim_customers

	--Find the total number of customers that has placed an order
	SELECT
	COUNT(DISTINCT customer_key)
	FROM gold.fact_sales

----Generate a Report that shows all key metrics of the business
	SELECT 
		'Total Sales' as measure_name,
		SUM(sales_amount) AS measure_value
	FROM gold.fact_sales
	UNION ALL
	SELECT 
		'Total Quantity' as measure_name,
		SUM(quantity) AS measure_value
	FROM gold.fact_sales
	UNION ALL
	SELECT 
		'Average Price' as measure_name,
		 AVG(price) AS measure_value
	FROM gold.fact_sales
	UNION ALL
	SELECT 
		'Total Orders' as measure_name,
		 COUNT(DISTINCT order_number) AS measure_value
	FROM gold.fact_sales
	UNION ALL
	SELECT 
		'Total Products' as measure_name,
		 COUNT(DISTINCT product_key) AS measure_value
	FROM gold.dim_products
	UNION ALL
	SELECT 
		'Total Customers' as measure_name,
		 COUNT(DISTINCT customer_key) AS measure_value
	FROM gold.dim_customers
	UNION ALL
	SELECT 
		'Total Customers' as measure_name,
		 COUNT(DISTINCT customer_key) AS measure_value
	FROM gold.fact_sales

--Magnitude Analysis
	--5.Aggregatle[Measure] By [Dimension]

	--Find the total customers by countries
	SELECT
	country,
	COUNT(customer_key) AS total_customers
	FROM gold.dim_customers
	GROUP BY country
	ORDER BY total_customers DESC

	--Find total customers by gender
	SELECT
	gender,
	COUNT(customer_key) AS total_customers
	FROM gold.dim_customers
	GROUP BY gender
	ORDER BY total_customers DESC;

	--Find total products by category
	SELECT
	category,
	COUNT(product_key) AS total_products
	FROM gold.dim_products
	GROUP BY category
	ORDER BY total_products DESC

	--What is the average costs in each category
	SELECT
	category,
	AVG(cost) AS total_cost
	FROM gold.dim_products
	GROUP BY category
	ORDER BY total_cost DESC

	--What is the total_revenue generated for each category
	SELECT
	p.category,
	SUM(f.sales_amount) AS total_revenue
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP BY p.category
	ORDER BY total_revenue DESC

	--What is the total revenue generated by each customer
	SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_customers c
	ON f.customer_key = c.customer_key
	GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
	ORDER BY total_revenue DESC

	--What is the toatl distribution of sold items across countries
	SELECT
	c.country,
	SUM(f.quantity) AS total_sold_items
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_customers c
	ON f.customer_key = c.customer_key
	GROUP BY 
	c.country
	ORDER BY total_sold_items DESC

--6.Ranking Analysis Top N - Bottom N
	--RANK[Dimension] By [measure]

	--Which 5 products generate the highest revenue
	SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP BY p.product_name
	ORDER BY total_revenue DESC

	--What are the 5 worst-performing products in terms of sales
	SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP BY p.product_name
	ORDER BY total_revenue ASC

	SELECT
	*
	FROM
		(SELECT
		p.product_name,
		SUM(f.sales_amount) AS total_revenue,
		ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_products
		FROM gold.fact_sales f
		LEFT JOIN gold.dim_products p
		ON p.product_key = f.product_key
		GROUP BY p.product_name)t
	WHERE rank_products <=5

	--Find the top 10 customers who have generated the highest revenue
	SELECT TOP 10
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_customers c
	ON f.customer_key = c.customer_key
	GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
	ORDER BY total_revenue DESC

	--The 3 customers with the fewest orders placed
	SELECT TOP 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT order_number) AS total_orders
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_customers c
	ON f.customer_key = c.customer_key
	GROUP BY 
	c.customer_key,
	c.first_name,
	c.last_name
	ORDER BY total_orders ASC
